name: Scan with Aquasec CLI Scanner

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  IMAGE_NAME: "andreazorzetto/demo-trivy-scan"

  # Specific scanner tag or saas-latest
  SCANNER_VERSION: "2506.2.10"

  # Registry name as configured in Aqua integrations
  IMAGE_REGISTRY_INTEGRATION: "Docker Hub"
  

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag $IMAGE_NAME:${{ github.sha }}

    # Downloading Trivy premium (Optionally use a mirrored binary)
    - name: Get Aquasec Trivy Premium
      run: wget --user ${{ secrets.AQUAREG_USER }} --password ${{ secrets.AQUAREG_PSWD }} https://download.aquasec.com/scanner/$SCANNER_VERSION/scannercli

    - name: Executable permissions
      run: chmod +x scannercli


      # Scanner authenticates to the server (-H) using a token (-A) but this can be replaced with user and password auth
      # image is registered if found compliant (--register-compliant) as belonging to the final registry (--registry).
      # the --local flag indicates a locally built image not available in the registry yet
    - name: Scan image
      run: ./scannercli scan -n -H ${{ secrets.AQUA_SERVER }} -A ${{ secrets.TOKEN }} --local --text --register-compliant --registry "$IMAGE_REGISTRY_INTEGRATION" $IMAGE_NAME:${{ github.sha }}

    - name: Tag and Push to Registry
      run: pass
