name: Scan with Aquasec Docker Scanner

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  IMAGE_NAME: "demo-local-build"
  SCANNER_VERSION: "latest-saas"

  # Registry name as configured in Aqua integrations
  IMAGE_REGISTRY_INTEGRATION: "Docker Hub"

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag $IMAGE_NAME:${{ github.sha }}

    # Downloading Trivy premium (Optionally use a mirrored image)
    - name: Docker login Aqua Registry
      run: docker login registry.aquasec.com -u ${{ secrets.AQUAREG_USER }} -p ${{ secrets.AQUAREG_PSWD }}

      # Scanner authenticates to the server (-H) using a token (-A) but this can be replaced with user and password auth
      # image is registered if found compliant (--register-compliant) as belonging to the final registry (--registry).
      # the --local flag indicates a locally built image not available in the registry yet
    - name: Scan image
      run: docker run --rm -v /var/run/docker.sock:/var/run/docker.sock registry.aquasec.com/scanner:$SCANNER_VERSION scan -n -H ${{ secrets.AQUA_SERVER }} -A ${{ secrets.TOKEN }} --local --text --register-compliant --registry $IMAGE_REGISTRY_INTEGRATION $IMAGE_NAME:${{ github.sha }}


    - name: Tag and Push to Registry
      run: pass
